export const genreList = [
  "*Non-fiction",
  "Action & Adventure",
  "Ancient",
  "Animals & Nature",
  "Anthologies",
  "Antiquity",
  "Asian Antiquity",
  "Atheism & Agnosticism",
  "Ballads",
  "Bibles",
  "Biography & Autobiography",
  "Business & Economics",
  "Chemistry",
  "Children's Fiction",
  "Children's Non-fiction",
  "Christian Fiction",
  "Christianity - Biographies",
  "Christianity - Commentary",
  "Christianity - Other",
  "Comedy",
  "Contemporary",
  "Crafts & Hobbies",
  "Crime & Mystery Fiction",
  "Detective Fiction",
  "Drama",
  "Dramatic Readings",
  "Early Modern",
  "Earth Sciences",
  "Education",
  "Elegies & Odes",
  "Epics",
  "Epistolary Fiction",
  "Erotica",
  "Essays & Short Works",
  "Exploration",
  "Family & Relationships",
  "Fictional Biographies & Memoirs",
  "Free Verse",
  "Games",
  "Gardening",
  "General Fiction",
  "Gothic Fiction",
  "Health & Fitness",
  "Historical",
  "Historical Fiction",
  "History",
  "House & Home",
  "Humor",
  "Law",
  "Letters",
  "Life Sciences",
  "Literary Collections",
  "Literary Criticism",
  "Literary Fiction",
  "Lyric",
  "Mathematics",
  "Medical",
  "Medieval",
  "Memoirs",
  "Middle Ages/Middle History",
  "Modern",
  "Modern (19th C)",
  "Modern (20th C)",
  "Music",
  "Narratives",
  "Nature",
  "Nautical & Marine Fiction",
  "Performing Arts",
  "Philosophy",
  "Plays",
  "Poetry",
  "Political Science",
  "Psychology",
  "Published 1800 -1900",
  "Published 1900 onward",
  "Published before 1800",
  "Reference",
  "Religion",
  "Religious Fiction",
  "Romance",
  "Sagas",
  "Satire",
  "School",
  "Science",
  "Science Fiction",
  "Short Stories",
  "Short non-fiction",
  "Short works",
  "Single Author Collections",
  "Sonnets",
  "Sports & Recreation",
  "Sports Fiction",
  "Technology & Engineering",
  "Tragedy",
  "Transportation",
  "Travel & Geography",
  "Travel Fiction",
  "True Crime",
  "War & Military",
  "War & Military Fiction",
  "Writing & Linguistics",
];
